### ISSUE TITLE
Add "shouldQueryWithFiltersCriteria" method

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/go-whosonfirst-spelunker-opensearch#2]
Necessary to allow for retrieving records by their `wof:id` value in full-text search.

Context: https://github.com/whosonfirst/go-whosonfirst-spelunker-httpd/issues/18

**Comment by straup** [comment]
Maybe, some day. In the meantime the immediate problem has been addressed elsewhere and there is no need at this time for a `shouldQueryWithFiltersCriteria` method.
