### ISSUE TITLE
Update "searchQueryCriteria" to use "shouldQueryWithFiltersCriteria"

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/go-whosonfirst-spelunker-opensearch#3]
Add optional wof:id=(N) query parameter to accommodate:

https://github.com/whosonfirst/go-whosonfirst-spelunker-httpd/issues/18

Blocked on issue #2

**Comment by thisisaaronland** [comment]
Maybe: https://github.com/whosonfirst/go-whosonfirst-spelunker-httpd/issues/18#issuecomment-2113372820

**Comment by straup** [comment]
This was addressed by: https://github.com/whosonfirst/go-whosonfirst-spelunker-httpd/releases/tag/v0.0.3
